# Generated by Django 6.0.3 on 2026-03-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
    ]
